### PR TITLE
Team members are an unordered set of users instead of a list

### LINKED ISSUE #288: Issues with Ordering of Team Members
### Terraform Version
terraform v1.1.3
opsgenie/opsgenie v0.6.8 (also confirmed with 0.6.9, 0.6.10 and reported with 0.6.2)

### Affected Resource(s)
- opsgenie_team

### Expected Behavior
For a plan after an apply, there should be no changes.

### Actual Behavior
Since yesterday. When doing a `terraform plan` it's showing required changes in the order of the member list. running a terraform apply will "apply" these changes, but further terraform plan operations still required changes in this ordering.

### Steps to Reproduce
1. Create HCL describing a team with more than one member
2. `terraform apply`
3. `terraform plan` - this should show no required changes.

### Important Factoids
* This appears to be because the order of the members presented by opsgenie is unstable - the actual change required in the ordering changes each time you plan, suggesting that the issue is caused by instability upstream. 
* This started on or around 9th Feb 2022
* This happens with older versions of terraform - so it's not a change in terraform which has caused this issue
* This did not happen previously with v0.6.8 of the provider

### PR DESCRIPTION
**Pull request by multani**
Members of a team are not sortable and there orders should not matter.

Currently, teams with several members may display changes every time Terraform is run, even if nothing changes (members configured in Terraform and/or members configured in Opsgenie itself.)

Furthermore, the current plan displays a list of user IDs that are being changed: this makes the plan even harder to read as the Terraform operator has to manually map which users correspond to which ID to understand the plan:

```hcl
  # opsgenie_team.main will be updated in-place
  ~ resource "opsgenie_team" "main" {
        id                       = "b7467f00-237e-42c3-8e0d-f0b1966f35aa"
        name                     = "main"
        # (2 unchanged attributes hidden)

      ~ member {
          ~ id   = "bb411771-e3e7-430a-aa04-383c2593e4f2" -> "0ab92f99-ac59-48f7-82d7-d71557111038"
            # (1 unchanged attribute hidden)
        }
      ~ member {
          ~ id   = "db346135-f57c-4292-a6d3-b06c0b9fa1ee" -> "bb411771-e3e7-430a-aa04-383c2593e4f2"
            # (1 unchanged attribute hidden)
        }
      ~ member {
          ~ id   = "7580b351-fe95-45d3-bdb8-feb5665e4a06" -> "db346135-f57c-4292-a6d3-b06c0b9fa1ee"
            # (1 unchanged attribute hidden)
        }
      ~ member {
          ~ id   = "0ab92f99-ac59-48f7-82d7-d71557111038" -> "7580b351-fe95-45d3-bdb8-feb5665e4a06"
            # (1 unchanged attribute hidden)
        }
    }
```

This pull request makes the list of members an *unordered set* of users instead of a *ordered list* and prevent this kind of change to appear in subsequent plans.

Fix #288

### CODE REVIEW

**Comment by tdfacer** [comment]
Looking forward to this, the PR came through just in time. Thanks @multani and Opsgenie team!

**Comment by darksilver43** [comment]
Super interested in getting this merged!

**Comment by SteezyCougar** [comment]
We're also super interested in this!

**Comment by mewm** [comment]
Looking forward to this! It's quite cumbersome currently with our amount of team members 🙈

**Review by fantom0005 — APPROVED** [review]

**Review by chochlovaslukas — APPROVED** [review]

**Review by fnuva — APPROVED** [review]

**Comment by multani** [comment]
Hm, apparently an important part of this patch is missing, and the provider crashes when trying to update team members. I'll make a fix very soon.

File: opsgenie/resource_opsgenie_team.go [hunk 1]
```diff
@@ -164,7 +164,7 @@ func resourceOpsGenieTeamUpdate(d *schema.ResourceData, meta interface{}) error
 		Description: description,
 	}
 
-	if len(d.Get("member").([]interface{})) > 0 && !d.Get("ignore_members").(bool) {
```
Comment (saifulwebid) [inline opsgenie/resource_opsgenie_team.go:167]: I think we also need this change for the `resourceOpsgenieTeamCreate` function, no?

Comment (multani) [reply opsgenie/resource_opsgenie_team.go:167]: Thanks a lot for spotting that! :man_facepalming:  (I admit I only tested the update of teams, not the creation :man_facepalming: )

I made another fix here https://github.com/opsgenie/terraform-provider-opsgenie/pull/321 and checked with the acceptance tests (should have done that since the beginning) and with a manual tests as well.
